sudo: required
dist: trusty

language: 
  - cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh
  - chmod +x cmake-3.10.3-Linux-x86_64.sh
  - ./cmake-3.10.3-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - PROJECT_DIR=`pwd`
  - git submodule update --init --merge
  - git clone https://github.com/google/googletest lib/benchmark/googletest
  - cd $PROJECT_DIR

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
  - make

script:
  - ./bin/main
  - ./test/tests
  - ./benchmark/benchmarks
